/* Generated by ./src/xlat/gen.sh from ./src/xlat/eventpoll_ioctl_cmds.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#define EPIOCSPARAMS _IOW(0x8A, 0x01, struct epoll_params)
#define EPIOCGPARAMS _IOR(0x8A, 0x02, struct epoll_params)
#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat eventpoll_ioctl_cmds in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data eventpoll_ioctl_cmds_xdata[] = {
#define EPIOCSPARAMS _IOW(0x8A, 0x01, struct epoll_params)
#define EPIOCGPARAMS _IOR(0x8A, 0x02, struct epoll_params)
};
static
const struct xlat eventpoll_ioctl_cmds[1] = { {
 .data = eventpoll_ioctl_cmds_xdata,
 .size = ARRAY_SIZE(eventpoll_ioctl_cmds_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
  ,
 .flags_strsz = 0
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
